source:
  awsEndpoint: "http://localhost:4567"
  awsRegion: "us-east-1"
  awsAccessKeyId: "dummy"
  awsSecretAccessKey: "dummy"
  streamInitialPosition: "TRIM_HORIZON"
  datastreamName: "flink-test"
  kinesaliteTimestampFix: True
sink:
  awsRegion: "us-east-1"
  awsEndpoint: "http://localhost:8000"
  tableName: "flink-test"
  cgTableName: "candidates"